---
collections:
  - name: infra.ee_utilities
  - name: awx.awx
  - name: infra.controller_configuration
  - name: infra.ah_configuration
  - name: containers.podman
  - name: redhat_cop.controller_configuration
...
