---
- name: Using role create job template
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: "{{ controller_hostname_var }}"
    controller_username: "{{ controller_username_var }}"
    controller_password: "{{ controller_password_var }}"
    controller_validate_certs: "{{ controller_validate_certs_var }}"
    controller_configuration_credentials_secure_logging: false
    controller_configuration_async_delay: 3
    controller_projects:
      - name: EE build project
        scm_type: git
        scm_url:  "{{ ee_builder_project_url_var }}"
        scm_branch: main
        scm_update_on_launch: true
        description: EE build project
        organization: Default
        wait: true
        update: true
    controller_inventories:
      - name: Controller Hosts
        organization: Default
      - name: Remote Build Servers
        organization: Default
    controller_hosts:
      - name: localhost
        inventory: Controller Hosts
        enabled: true
        variables:
          ansible_connection: local
          ansible_python_interpreter: '{{ ansible_playbook_python }}'
      - name: "{{ remote_builder_hostname_var }}"
        inventory: Remote Build Servers
        enabled: true
        variables:
          ansible_connection: ssh
          ansible_ssh_user: "{{ remote_builder_username_var }}"
          ansible_ssh_pass: "{{ remote_builder_password_var }}"
    controller_credential_types:
      - name: Registery Credentials
        description: REST API Credential
        kind: cloud
        inputs:
          fields:
            - id: base_registery_username
              type: string
              label: RH Registery Username
            - id: base_registery_password
              type: string
              label: RH Registery Password
              secret: true
            - id: ee_registry_username
              type: string
              label: AH Registery Username
            - id: ee_registry_password
              type: string
              label: AH Registery Password
              secret: true
            - id: ee_ah_host
              type: string
              label: AH Hostname
            - id: ee_ah_token
              type: string
              label: AH Token
              secret: true
            - id: ee_validate_certs
              type: boolean
              default: false
              label: Validate certs
          required:
            - base_registery_username
            - base_registery_password
        injectors:
          extra_vars:
            ee_base_registry_username: !unsafe "{{ base_registery_username }}"
            ee_base_registry_password: !unsafe "{{ base_registery_password }}"
            ee_registry_username: !unsafe "{{ ee_registry_username }}"
            ee_registry_password: !unsafe "{{ ee_registry_password }}"
            ee_validate_certs: !unsafe "{{ ee_validate_certs }}"
            ah_host: !unsafe "{{ ee_ah_host }}"
            ah_token: !unsafe "{{ ee_ah_token }}"
    controller_credentials:
      - credential_type: Registery Credentials
        name: Execution Build Credentials
        organization: Default
        inputs:
          base_registery_username:  "{{ base_registery_username_var }}"
          base_registery_password:  "{{ base_registery_password_var }}"
          ee_registry_username: "{{ ee_registry_username_var }}"
          ee_registry_password: "{{ ee_registry_password_var }}"
          ee_validate_certs: "{{ ee_validate_certs_var }}"
          ee_ah_host: "{{ ah_host_var }}"
          ee_ah_token: "{{ ah_token_var }}"
      - credential_type: Red Hat Ansible Automation Platform
        name: Controller Credential
        organization: Default
        inputs:
          host: "{{ controller_hostname_var}}"
          username: "{{ controller_username_var }}"
          password: "{{ controller_password_var }}"
          verify_ssl: "{{ controller_validate_certs_var }}"
    controller_templates:
      - name: Execution Environment Builder
        job_type: run
        inventory: Remote Build Servers
        credentials:
          - Execution Build Credentials
        project: EE build project
        execution_environment: Minimal execution environment
        playbook: ee_builder_controller.yaml
        extra_vars:
          ee_registry_dest: "{{ ee_registry_dest_var }}"
          ee_builder_dir_clean: true
      - name: Push Execution Environments to Controller
        job_type: run
        inventory: Controller Hosts
        credentials:
          - Controller Credential
        project: EE build project
        execution_environment: Minimal execution environment
        playbook: push_to_controller.yaml
    controller_workflows:
      - name: Update Execution Environments
        workflow_nodes:
          - identifier: Build EE's
            unified_job_template:
              name: Execution Environment Builder
              type: job_template
              organization:
                name: Default
            related:
              success_nodes:
                - identifier: Push EE's to controller
          - identifier: Push EE's to controller
            unified_job_template:
              name: Push Execution Environments to Controller
              type: job_template
              organization:
                name: Default
      - name: Test Generated Image Template
        job_type: run
        inventory: Controller Hosts
        project: EE build project
        playbook: test_image_playbook.yaml  # Name of your test playbook
        verbosity: 1
        execution_environment: Custom EE  # Specify the execution environment here
        survey_enabled: true
        survey_spec:
          name: Enter Name for Hello statement
          description: This is a test survey
          spec:
            - question_name: Name
              question_description: Enter your name
              required: true
              type: text
              variable: username
              min: 0
              max: 256
            # Add more survey questions as needed
        extra_vars:
          username: "{{ username_var }}"  # Example of how to use extra_vars
  roles:
    - infra.controller_configuration.credential_types
    - infra.controller_configuration.credentials
    - infra.controller_configuration.inventories
    - infra.controller_configuration.hosts
    - infra.controller_configuration.projects
    - infra.controller_configuration.job_templates
    - infra.controller_configuration.workflow_job_templates
...
