- name: Playbook to create custom EE For AWS Roles
  hosts: all
  gather_facts: false
  vars:
    # For controller configuration definition
    ee_reg_credential: Automation Hub Container Registry
    ee_base_image: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
    ee_list:
      - name: custom_ee
        alt_name: Custom EE
        tag: 1-11-21-2
        # base_image
        dependencies:
          system:
            - python38-requests [platform:centos-8 platform:rhel-8]
            - python38-pyyaml [platform:centos-8 platform:rhel-8]
          python:
            - pytz  # for schedule_rrule lookup plugin
            - python-dateutil>=2.7.0  # schedule_rrule
            - awxkit  # For import and export modules
            - boto3
          galaxy:
            collections:
              - name: amazon.aws
        build_steps:
          prepend_final:
            - RUN whoami
            - RUN cat /etc/os-release
          append_final:
            - RUN whoami
            - RUN echo This is a post-install command!
  roles:
    - infra.ee_utilities.ee_builder


    