---
- name: Using role create job template
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: "{{ controller_hostname_var }}"
    controller_username: "{{ controller_username_var }}"
    controller_password: "{{ controller_password_var }}"
    controller_validate_certs: "{{ controller_validate_certs_var }}"
    controller_configuration_credentials_secure_logging: false
    controller_projects:
      - name: EE build project
        scm_type: git
        scm_url: "{{ ee_builder_project_url_var }}"
        scm_branch: main
        scm_update_on_launch: true
        description: EE build project
        organization: Default
        wait: true
        update: true
      - name: Ansible Roles for AWS Infrastructure Creation
        scm_type: git
        scm_url: "{{ project_url_var }}"
        scm_branch: master
        scm_update_on_launch: true
        description: Ansible Roles for AWS Infrastructure Creation
        organization: Default
        wait: true
        update: true
    controller_inventories:
      - name: Controller Hosts
        organization: Default
      - name: Remote Build Servers
        organization: Default
    controller_hosts:
      - name: localhost
        inventory: Controller Hosts
        enabled: true
        variables:
          ansible_connection: local
          ansible_python_interpreter: '{{ ansible_playbook_python }}'
      - name: "{{ remote_builder_hostname_var }}"
        inventory: Remote Build Servers
        enabled: true
        variables:
          ansible_connection: ssh
          ansible_ssh_user: "{{ remote_builder_username_var }}"
          ansible_ssh_pass: "{{ remote_builder_password_var }}"
    controller_credential_types:
      - name: AWS Credentials  # New credential kind for AWS
        description: AWS Access and Secret Key Credential
        kind: cloud
        inputs:  # Providing it as an array, even with a single input field
          fields:
            - id: aws_access_key_id
              type: string
              label: AWS Access Key ID
              secret: true
            - id: aws_secret_access_key
              type: string
              label: AWS Secret Access Key
              secret: true
            - id: aws_default_region
              type: string
              label: AWS Default Region
        required:
          - aws_access_key_id
          - aws_secret_access_key
          - aws_default_region
        injectors:
          extra_vars:
            aws_access_key_id: !unsafe "{{ aws_access_key_id }}"
            aws_secret_access_key: !unsafe "{{ aws_secret_access_key }}"
            aws_default_region: !unsafe "{{ aws_default_region }}"
      - name: Registery Credentials
        description: REST API Credential
        kind: cloud
        inputs:
          fields:
            - id: base_registery_username
              type: string
              label: RH Registery Username
            - id: base_registery_password
              type: string
              label: RH Registery Password
              secret: true
            - id: ee_registry_username
              type: string
              label: AH Registery Username
            - id: ee_registry_password
              type: string
              label: AH Registery Password
              secret: true
            - id: ee_ah_host
              type: string
              label: AH Hostname
            - id: ee_ah_token
              type: string
              label: AH Token
              secret: true
            - id: ee_validate_certs
              type: boolean
              default: false
              label: Validate certs
          required:
            - base_registery_username
            - base_registery_password
        injectors:
          extra_vars:
            ee_base_registry_username: !unsafe "{{ base_registery_username }}"
            ee_base_registry_password: !unsafe "{{ base_registery_password }}"
            ee_registry_username: !unsafe "{{ ee_registry_username }}"
            ee_registry_password: !unsafe "{{ ee_registry_password }}"
            ee_validate_certs: !unsafe "{{ ee_validate_certs }}"
            ah_host: !unsafe "{{ ee_ah_host }}"
            ah_token: !unsafe "{{ ee_ah_token }}"
    controller_credentials:
      - credential_type: Registery Credentials
        name: Execution Build Credentials
        organization: Default
        inputs:
          base_registery_username:  "{{ base_registery_username_var }}"
          base_registery_password:  "{{ base_registery_password_var }}"
          ee_registry_username: "{{ ee_registry_username_var }}"
          ee_registry_password: "{{ ee_registry_password_var }}"
          ee_validate_certs: "{{ ee_validate_certs_var }}"
          ee_ah_host: "{{ ah_host_var }}"
          ee_ah_token: "{{ ah_token_var }}"
      - credential_type: AWS Credentials  # Use the new credential kind
        name: AWS Execution Build Credentials
        organization: Default
        inputs:
          aws_access_key_id: "{{ aws_access_key_id }}"
          aws_secret_access_key: "{{ aws_secret_access_key }}"
          aws_default_region: "{{ aws_default_region }}"
    controller_templates:
      - name: Execution Environment Builder
        job_type: run
        inventory: Remote Build Servers
        credentials:
          - Execution Build Credentials
        project: EE build project
        playbook: ee_builder_controller_aws_roles.yaml
        verbosity: 1
        extra_vars:
          ee_registry_dest: "{{ ee_registry_dest_var }}"
      - name: Push Execution Environments to Controller
        job_type: run
        inventory: Controller Hosts
        credentials:
          - Controller Credential
        project: EE build project
        execution_environment: Minimal execution environment
        playbook: push_to_controller.yaml
        extra_vars:
          ee_registry_dest: "{{ ee_registry_dest_var }}"
      - name: Deploy AWS VPC and Subnets
        job_type: run
        inventory: Controller Hosts
        execution_environment: Minimal execution environment
        credentials:
          - AWS Execution Build Credentials
        project: Ansible Roles for AWS Infrastructure Creation
        playbook: aws.yaml  # Name of your test playbook
        verbosity: 1
        execution_environment: Custom EE  # Specify the execution environment here
        extra_vars:
          VPC_NAME: test  # Name of the VPC
          VPC_REGION: us-east-2  # Region where the VPC will be created (Ohio)
          VPC_CIDR: "172.25.0.0/16"  # CIDR block for the VPC
          VPC_CLASS_DEFAULT: "172.25"  # Default class for IP addresses within the VPC
          vpc_name: "{{ VPC_NAME }}"  # Name of the VPC (using the VPC_NAME variable)
          vpc_region: "{{ VPC_REGION }}"  # Region of the VPC (using the VPC_REGION variable)
          vpc_cidr_block: "{{ VPC_CIDR }}"  # CIDR block of the VPC (using the VPC_CIDR variable)
          public_cidr_1: "{{ VPC_CLASS_DEFAULT }}.10.0/24"  # CIDR block for Public Subnet-1
          public_az_1: "{{ vpc_region }}a"  # Availability Zone for Public Subnet-1
          public_cidr_2: "{{ VPC_CLASS_DEFAULT }}.20.0/24"  # CIDR block for Public Subnet-2
          public_az_2: "{{ vpc_region }}b"  # Availability Zone for Public Subnet-2
          private_cidr_1: "{{ VPC_CLASS_DEFAULT }}.30.0/24"  # CIDR block for Private Subnet-1
          private_az_1: "{{ vpc_region }}a"  # Availability Zone for Private Subnet-1
          private_cidr_2: "{{ VPC_CLASS_DEFAULT }}.40.0/24"  # CIDR block for Private Subnet-2
          private_az_2: "{{ vpc_region }}b"  # Availability Zone for Private Subnet-2
          public_vpc_subnets:
            - cidr: "{{ public_cidr_1 }}"  # CIDR block for Public Subnet-1
              az: "{{ public_az_1 }}"  # Availability Zone for Public Subnet-1
              resource_tags: { "Name":"{{ vpc_name }}-{{ public_az_1 }}-public_subnet-1", "Type":"Public", "Alias":"Public_Subnet_1" }  # Resource tags for Public Subnet-1
            - cidr: "{{ public_cidr_2 }}"  # CIDR block for Public Subnet-2
              az: "{{ public_az_2 }}"  # Availability Zone for Public Subnet-2
              resource_tags: { "Name":"{{ vpc_name }}-{{ public_az_2 }}-public-subnet-2", "Type":"Public", "Alias":"Public_Subnet_2" }  # Resource tags for Public Subnet-2

          private_vpc_subnets:
            - cidr: "{{ private_cidr_1 }}"  # CIDR block for Private Subnet-1
              az: "{{ private_az_1 }}"  # Availability Zone for Private Subnet-1
              resource_tags: { "Name":"{{ vpc_name }}-{{ private_az_1 }}-private-subnet-1", "Type":"Private", "Alias":"Private_Subnet_1" }  # Resource tags for Private Subnet-1
            - cidr: "{{ private_cidr_2 }}"  # CIDR block for Private Subnet-2
              az: "{{ private_az_2 }}"  # Availability Zone for Private Subnet-2
              resource_tags: { "Name":"{{ vpc_name }}-{{ private_az_2 }}-private-subnet-2", "Type":"Private", "Alias":"Private_Subnet_2" }  # Resource tags for Private Subnet-2
  roles:
    - infra.controller_configuration.credential_types
    - infra.controller_configuration.credentials
    - infra.controller_configuration.inventories
    - infra.controller_configuration.hosts
    - infra.controller_configuration.projects
    - infra.controller_configuration.job_templates
...
