---
- name: Run Microshift rpm install role
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Check if system is registered
      command: subscription-manager identity
      register: subscription_status
      become: true
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Login and register system
      redhat_subscription:
        state: present
        username: "{{ rhel_username  }}"
        password: "{{ rhel_password  }}"
      when: subscription_status.rc != 0
      become: true

    - name: Auto-attach subscription
      redhat_subscription:
        state: auto-attach
      become: true
      when: subscription_status.rc != 0

    - name: Enable sudo subscription-manager config
      command: sudo subscription-manager config --rhsm.manage_repos=1
      become: true
      when: subscription_status.rc != 0
      
    - name: Install required packages
      become: true
      package:
        name:
          - git
          - vim
          - unzip
          - wget
          - bind-utils
          - python3-pip
          - tar
          - util-linux-user
          - gcc
          - python3-devel
          - podman
          - ansible-core
          - make
          - tmux
          - ncurses-devel
          - curl
        state: present
      become: true
      tags: install_packages

    - name: Create openshift-pull-secret file
      copy:
        content: "{{ openshift_pull_secret }}"
        dest: "$HOME/openshift-pull-secret"

    - name: Install Microshift on rpm based system
      ansible.builtin.import_role:
        name: edge.microshift.rpm_install