---
- name: Run Microshift rpm install role
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if system is registered
      command: subscription-manager identity
      register: subscription_status
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Login and register system
      redhat_subscription:
        state: present
        username: "{{ rhel_username  }}"
        password: "{{ rhel_password  }}"
        auto_attach: yes
      become: true
      when: subscription_status.rc != 0

    - name: Enable sudo subscription-manager config
      command: sudo subscription-manager config --rhsm.manage_repos=1
      become: true


    - name: Auto Attach subscription
      command: sudo subscription-manager attach --auto
      become: true
      
    - name: Install required packages
      become: true
      package:
        name:
          - git
          - vim
          - unzip
          - wget
          - bind-utils
          - python3-pip
          - tar
          - util-linux-user
          - gcc
          - python3-devel
          - podman
          - ansible-core
          - make
          - tmux
          - ncurses-devel
          - curl
        state: present
      become: true
      tags: install_packages

    - name: Create openshift-pull-secret file
      copy:
        content: "{{ openshift_pull_secret }}"
        dest: "/home/ec2-user/pull-secret.txt"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

     - name: exit is pull-secret.txt is not present in the home directory
       ansible.builtin.fail:
         msg: "pull-secret.txt is not present in the home directory"
       when: not ansible.builtin.stat(path="/home/ec2-user/pull-secret.txt").exists

    - name: Debug Installing rpm version 
      debug:
        msg: "Installing rpm version {{ rpm_install_version }}"

    - name: Install Microshift on rpm based system
      ansible.builtin.import_role:
        name: edge.microshift.rpm_install
      become: true
      vars:
        rpm_install_version: "{{ rpm_install_version }}"